Fix lumitech brightness and temperature
UncleSamSwiss/ioBroker.loxone pull request #544
Opened 2024-05-13 07:16 UTC by Arcticon

Fixes UncleSamSwiss/ioBroker.loxone#150

2024-05-13 07:22 UTC, raintonr requested changes

2024-05-13 07:22 UTC, raintonr commented on src/main.ts
> +    ackTimer: ioBroker.Timeout | undefined;
Think I have mentioned before: please don't change null to undefined.

2024-05-13 07:22 UTC, raintonr commented on src/controls/ColorpickerBase.ts
> +        this.adapter.log.info(
This looks like debug, not info.

2024-05-13 10:26 UTC, Arcticon commented on src/controls/ColorpickerBase.ts
> +        this.adapter.log.info(
i need to remove this

2024-05-13 13:26 UTC, raintonr commented on src/main.ts
> +    ackTimer: ioBroker.Timeout | undefined;
Nope. As discussed has to be undefined now.

2024-05-13 15:04 UTC, raintonr approved these changes

2024-05-13 15:26 UTC, raintonr commented
I don't see why one needs to try `lumitechColorToBrightnessTemperature` and then fall back to `loxoneColorToBrightnessTemperature`.

Surely either the control is Lumitech or it is not? Is there some error or other logic in the Loxone Miniserver that sometimes reports the wrong control type? The referenced issue doesn't seem to mention this.

**IF** it turns out that the Loxone Miniserver sometimes incorrectly reports the control type then personally I would have merged `loxoneColorToBrightnessTemperature` & `lumitechColorToBrightnessTemperature` into one function and have that try to match `(lumitech|temp)\((\d+),(\d+)\)`.

2024-05-13 18:25 UTC, Arcticon commented
you are correct. will change

2024-05-14 05:57 UTC, raintonr commented
> the loxone UI always reported `temp(x,y)` instead of `lumitech(x,y)`. i sadly dont know why 🫤

Yeah. Loxone are annoying sometimes :disappointed: 

At least you have moved the 'or' logic from each call into `lumitechOrLoxoneColorToBrightnessTemperature` though so about the best we can do without Loxone actually doing what it says it will.

2024-05-14 05:57 UTC, merged